### PR TITLE
added #1644 simple function

### PR DESCRIPTION
**Pull request by ytetsuro**
> Please describe what your pull request does and which issue you're targeting

#1644

Although it is not a rich UI, I made it possible to post the diff as a comment.

add following comment when click diff line.

<pre>
&lt;a href="path/to/pull/1#diff-hash"&gt;
```diff
 diff string
```
&lt/a&gt;
</pre>

### CODE REVIEW

**Comment by Unknwon** [comment]
Thank for the PR but I think diff style code block is supported by nature already: https://try.gogs.io/unknwon/test2/issues/1

image

**Comment by ytetsuro** [comment]
Thank you reply.

My PR does not provide diff style code block.
Use the diff style code block, click on the line of code to create the diff and link for that place, make Gogs' PR comment handy.
The code attached as an image is a code to create a comment on the clicked place using diff style code block.

**Comment by Unknwon** [comment]
Hmm, maybe a gif can explain what has changed better?

**Comment by Unknwon** [comment]
Simply put, I still have no idea of the purpose of changes proposed in this PR.

**Comment by ytetsuro** [comment]
> Simply put, I still have no idea about the purpose of changes proposed in this PR.

I understand.
Thank you review and reply.

I hope this PR will be helpful for consideration.
I am developing it using Gogs which made this modification, but  very convenient to comment.
I personally it is feel it is more useful than Github.
It feels strong when doing similar comments on multiple lines.

**Comment by Unknwon** [comment]
Thanks for the PR but I do not think there is any chance to merge it. But you may still use it in your version of Gogs for your convenience.

**Pull request closed without merging**
