### PR TITLE
Remove branch prefix from SHA URL

### LINKED ISSUE #6300: Auto generated URL of commit SHA references link to wrong address
**Describe the bug**
Auto generated URL of commit SHA references in markdown link to wrong address

**Gogs version and commit**
Gogs  0.11.91.0811

**Git version**
Git 2.24.1.windows.2

**Operating system**
Windows 10 Home (Chinese) 19041.450

**Database**
Unknown

**To Reproduce**
1. Edit README.md file locally, add line with a valid commit SHA value, save file.
2. Commit and push README.md to repository
3. View the render page of README.md in Gogs
4. Click the link of commit SHA references, the browser jump to wrong 404 page

**Can you reproduce the bug at https://try.gogs.io?**
No try yet

**Expected behavior**
A link with correct URL to commit SHA references.

**Actual behavior**
A link with wrong URL, unnecessary 'src/develop' path in the URL.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by zhukovra**
Resolves #6300

### CODE REVIEW

**Comment by laojianzi** [comment]
Expected: https://domain/owner/repo/commit/sha1

**Comment by zhukovra** [comment]
@laojianzi you're right. Fixed.

**Comment by laojianzi** [comment]
@zhukovra nice!

But `strings.LastIndex(urlPrefix, "/src/")` will failed on batch name include `/src`

e.g: batch name `/6349/src/issue`

So I refactored the code by pull #6350

**Comment by zhukovra** [comment]
@laojianzi thank you. It's hard to develop with passing maps across lot of functions (I think we should use structs) and without local installation (but I'll setup it soon).

**Comment by laojianzi** [comment]
> @laojianzi thank you. It's hard to develop with passing maps across lot of functions (I think we should use structs) and without local installation (but I'll setup it soon).

Yes, @unknwon thinks so too

Hope a better refactor and the smallest difference

thx !!!

**Comment by unknwon** [comment]
@zhukovra Thanks for the PR!

I'm closing this PR in favor of #6350, and co-authored you on that.

**Pull request closed without merging**
