### PR TITLE
Update user.go

### PR DESCRIPTION
**Pull request by mvrahden**
## Problem
failed to receive OS-Username on some docker OS before

## Description
updates the method to retrieve the USER-name.

## What changed?
This version initially triggers the native user-object and if this fails queries the OS-Env. Instead of relying on a solution purely build on OS-Environment variables.

### CODE REVIEW

**Comment by Unknwon** [comment]
`user.Current()` uses CGO, and has problem with cross-compilation.

**Comment by Unknwon** [comment]
What we found was we can build, but when try to start in target platform (e.g. build on macOS and target is linux amd64), it says something like "not implemented" (if I remember correctly).

**Comment by mvrahden** [comment]
Ok, I understand! Thank you very much for the answer :) 💯

**Comment by FlyingOnion** [comment]
Sorry for adding comment after so long. I have the same problem, and my solution is to add a environment `USER=git` when I launch a container. I know `git` may be the default user of gogs for the time being, but are there any better solutions if custom users are added for gogs?

**Comment by unknwon** [comment]
> I have the same problem, and my solution is to add a environment `USER=git` when I launch a container.

@FlyingOnion: Not sure what you're asking exactly... but this looks correct to me :D

**Pull request closed without merging**
