### PR TITLE
fix #5229

### LINKED ISSUE #5229: Webhook not cleaned up when delete repository
models/repo.go
DeleteRepository 
漏了个 webhook

@Unknwon

### PR DESCRIPTION
**Pull request by naiba**
Webhook and hook_task not cleaned up when delete repository

### CODE REVIEW

**Comment by Unknwon** [comment]
I can only merge this later because we also need to do migration which "gc"s old unlinked records in database table.

**Comment by naiba** [comment]
@Unknwon wen ru gou

**Comment by naiba** [comment]
@Unknwon #5277 clean unlinked webhook and hook_tasks

**Comment by Unknwon** [comment]
You're are so good...

**Pull request merged**
