### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ramosisw**
Fix Typo when add Discord Webhook

### CODE REVIEW

**Comment by unknwon** [comment]
Thank you very much for the PR, and good catch!

However, I cannot merge this because the changes to localization of this language must be made in Crowdin, you can find related documentation here: https://gogs.io/docs/features/i18n

**Comment by unknwon** [comment]
I updated for you: https://crowdin.com/translate/gogs/1/enus-es#q=settings.add_discord_hook_desc

I'll pull changes from Crowdin tonight after work and push to this repository.

**Comment by ramosisw** [comment]
Great! i will close PR

**Comment by unknwon** [comment]
Changes are included in the https://github.com/gogs/gogs/commit/1c82c42cb357b4d1c190a30346f52e11427e8470.

**Pull request closed without merging**
