### PR TITLE
[Docker][RFC] Use upstream go image

### PR DESCRIPTION
**Pull request by J0WI**
There is no need to build go from source. Docker is already doing this and provides a well supported base image. Those official images are also continuously maintained and scanned for security issues.

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

### CODE REVIEW

**Comment by Unknwon** [comment]
Hi, how is the final image size built based on official Go image?

**Comment by J0WI** [comment]
It's 391MB on my amd64 machine. The golang base image (1.8) is 78MB, so there are still many ways to improve dependencies.
1.8 is no longer supported btw.

**Comment by Unknwon** [comment]
It seems way too large than the current size (60MB)...

**Comment by J0WI** [comment]
How do you measure it? When I build the current master it's much bigger than this (I get the size from `docker images`).

**Comment by Unknwon** [comment]
In case of local size of current image (just pulled):

```
➜  ~ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
gogs/gogs                      latest              f23a2efe3e3f        About an hour ago   156MB
```

**Comment by Nols1000** [comment]
I think the reason for the size of the image is that the official golang:alpine image contains the source of the packages to build go applications. I think the best way to build a minimized image would be to compile a binary with all dependencies built in (not linked) and run it in a "scratch"-image or for a little more script support in "busybox" or "alpine". Check out this blog post [https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/](https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/).

**Comment by J0WI** [comment]
> I think the reason for the size of the image is that the official golang:alpine image contains the source of the packages to build go applications.

I think that's expected that others can use this image as a base for their own changes.

**Comment by Unknwon** [comment]
The base image of Go will make Gogs's image way too large and since that's not necessary, I don't think we should change our based image.

**Comment by Unknwon** [comment]
By a quick look, isn't it the way it's been done right now?

**Comment by J0WI** [comment]
I don't think so. There is an [example](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds) for a go application, that looks much simpler that the current procedure with build shell scripts. The upstream image also supports a range of different architectures out of the box.

**Comment by Unknwon** [comment]
I the current multi-stage Docker build is doing a good job.

**Comment by J0WI** [comment]
Note: this may not work for official images: https://github.com/docker-library/official-images/issues/3383

**Pull request closed without merging**
