### PR TITLE
ui: remove useless "Cancel" buttons

### PR DESCRIPTION
**Pull request by yardenshoham**
Port of go-gitea/gitea#21381

### Describe the pull request

There's no need for a cancel button, just leave the page.

### Checklist

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct) by submitting this pull request.
- [X] I have read and acknowledged the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks for the PR, could you explain why it is "useless"?

If "cancel" buttons are not worth it (not yet convinced), we should remove all of them (at least three including this one, "New Repository", "New Migration" and "New Organization"), not just this single one.

Aside from that, I like the "make it better" approach more that is described in https://github.com/go-gitea/gitea/issues/21131, i.e. takes user back to the previous page.

**Comment by yardenshoham** [comment]
It's useless because there is no reason to use it. If I want to go to the home page I'll just go back

**Comment by unknwon** [comment]
Can you also remove other "cancel" buttons from "New Migration" and "New Organization" pages?

**Comment by yardenshoham** [comment]
> Can you also remove other "cancel" buttons from "New Migration" and "New Organization" pages?

Done

**Review by unknwon — APPROVED** [review]
Thanks for the followup!

**Pull request merged**
