### PR TITLE
Invalid PR

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
### scope
- fixed some typos & misspellings
- minor grammar improvements

Sorry for the small PR! :)

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks for the PR!

> Sorry for the small PR! :)

Small PRs are the best :)

---

Could you run `make generate` in repository root and commit new changes produced by the command?

**Comment by DRSDavidSoft** [comment]
@unknwon Sorry for the delay, I have committed the generated files 😄

**Comment by unknwon** [comment]
No worries!

These changes do not look right to me:

image

And the one that is supposed to be updated didn't change: https://github.com/gogs/gogs/blob/master/internal/assets/conf/conf_gen.go

**Comment by unknwon** [comment]
Hmm, what about you revert the new changes, and I'll push the commit for you after that.

**Comment by DRSDavidSoft** [comment]
@unknwon Sorry for the (even) longer delay getting back to you.  I'm now closing this PR in favor of #6237.  
Please remove the labels from this one, and move them to the new one.

Thank you!

**Pull request closed without merging**
