### PR TITLE
Adding hilighting type and lines count to file view header #2207

### PR DESCRIPTION
**Pull request by spectre013**
Added type of file highlighting being applied when viewing a file, When multiple formats are applied i.e. HTML and JavaScript the parent type will be shown (HTML). 

Also added number of lines in the file to the header. 

gog-fileheaderupdate

### CODE REVIEW

**Comment by Unknwon** [comment]
Can you attach a screenshot of viewing a README.md file?

**Comment by Unknwon** [comment]
Hi, can you rebase instead of merging? Currently it is extremely hard to review.

**Comment by spectre013** [comment]
image

**Comment by Androbin** [comment]
@spectre013 Do you have trouble rebasing?

**Pull request closed without merging**
