### PR TITLE
Added romanian language file

### PR DESCRIPTION
**Pull request by autotim**
Updated conf/locale/locale_ro_RO.ini, translated 100 lines.

### CODE REVIEW

**Comment by unknwon** [comment]
Thank you for the kind contribution!

Unfortunately, you might have not read the pull request template which has a link to https://github.com/gogs/gogs/wiki/Contributing-Code#those-we-do-not-accept.

**Comment by autotim** [comment]
> Thank you for the kind contribution!
> 
> Unfortunately, you might have not read the pull request template which has a link to https://github.com/gogs/gogs/wiki/Contributing-Code#those-we-do-not-accept.

Okay. Now I read the article. Can you add romanian language here please https://crowdin.com/project/gogs

**Comment by unknwon** [comment]
I will add and upload INI file for you this time :) (later tonight)

**Comment by autotim** [comment]
> I will add and upload INI file for you this time :) (later tonight)

All good, thanks :)

**Comment by unknwon** [comment]
Here you go: https://crowdin.com/translate/gogs/1/enus-ro

And feel free to add yourself to this file: https://github.com/gogs/gogs/blob/master/conf/locale/TRANSLATORS

**Pull request closed without merging**
