### PR TITLE
gitutil: strip SSH port from submodule URL when rendering for HTML link

### PR DESCRIPTION
**Pull request by TheDarkUndoing**
## Describe the pull request

This is the bug fix for #4941 

Link to the issue: fixes https://github.com/gogs/gogs/issues/4941#issuecomment-1448416430

## Checklist

- [x] I agree to follow the [Code of Conduct](https://go.dev/conduct) by submitting this pull request.
- [x] I have read and acknowledge the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).
- [x] I have added test cases to cover the new code or have provided the test plan.

### CODE REVIEW

**Comment by TheDarkUndoing** [comment]
@unknwon could you take a look at this, I want to make sure the changes effect the front end, is there a CICD workflow for me to test a build with my changes?

**Comment by unknwon** [comment]
> @unknwon could you take a look at this, I want to make sure the changes effect the front end, is there a CICD workflow for me to test a build with my changes?

I just approved the CI jobs for this PR. Will take a closer this week if all checks passed, thank you!

**Comment by TheDarkUndoing** [comment]
Looks like the lint failed, I formatted and commited the change.

**Comment by TheDarkUndoing** [comment]
> > @unknwon could you take a look at this, I want to make sure the changes effect the front end, is there a CICD workflow for me to test a build with my changes?
> 
> I just approved the CI jobs for this PR. Will take a closer at the code this week if all checks passed, thank you!

Looks like the lint failed, I formatted and commited the change. Ready for CI job to be run again

**Review by unknwon — APPROVED** [review]
Thank you!

**Comment by TheDarkUndoing** [comment]
This doesn't fix when a host has a port. The change I made would fix this. Your simpler solution does not fix this.

**Comment by TheDarkUndoing** [comment]
@unknwon Can we reopen this to properly address the bug?

**Comment by unknwon** [comment]
@TheDarkUndoing My bad, will take another look!

**Comment by TheDarkUndoing** [comment]
@unknwon my original change should address the issue

**Comment by unknwon** [comment]
> This doesn't fix when a host has a port.

@TheDarkUndoing - what is an example of "a host has a port"?

**Comment by TheDarkUndoing** [comment]
For an example the gogs server is hosted on port 8080. The url for the host is {gogs host}:8080. I dont think there is a way to retain the port with the way submodule.go is written.

**Comment by unknwon** [comment]
> For an example the gogs server is hosted on port 8080. The url for the host is {gogs host}:8080. I dont think there is a way to retain the port when parsing an ssh url with the way submodule.go is written. I think the baseUrl host does not retain the port number if it isn't hosted on port 80. It is written assuming that port 80 is the only port that would be hosting gogs

Yes, but how is your original version handles it? Here we are only dealing with ssh:// urls, there is no information to tell whether the http:// should have a port or not. 🤔

**Comment by TheDarkUndoing** [comment]
after reviewing my last change,  I was wrong my changes dont effect that. I think we would need some kind of "global" variable or env that holds the proper host URL. That may already exist, I havent checked.

**Comment by unknwon** [comment]
> after reviewing my last change, I was wrong my changes dont effect that. I think we would need some kind of "global" variable or env that holds the proper host URL. That may already exist, I havent checked.

Top off my head I think having a pre-defined "global" list is suboptimal, it is unpractical to know the host URL info ahead of time. I think extend the `.gitmodules` to include a non-SSH URL would be better (not final).

---

Since the new issue is unrelated to this thread, I'd recommend to file a new issue to address that (if we want to).

**Pull request merged**
