### PR TITLE
Apply hardening for systemd unit

### PR DESCRIPTION
**Pull request by khomutsky**
Disallow modifications to the system, disallow access to devices and separate temporary directory.

ProtectSystem=full # Make /boot, /etc and /usr read-only
PrivateDevices=yes # Disallow access to devices
PrivateTmp=yes # Make separate /tmp directory for gogs.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thank you!

**Comment by CRCinAU** [comment]
I would suggest one more:

NoNewPrivileges=true

**Comment by Unknwon** [comment]
@CRCinAU a PR would great!

**Comment by CRCinAU** [comment]
I think I've done that right - first time doing a PR on github.

**Pull request merged**
