### PR TITLE
#5579

### PR DESCRIPTION
**Pull request by mvpenzin**
Correct translate "Issues" is "Задачи". No "Обсуждения".

### CODE REVIEW

**Comment by 06Games** [comment]
As per the [instruction](https://github.com/gogs/gogs/wiki/Contributing-Code#those-we-do-not-accept), your pull request will be rejected, I recommend you make these changes on [Crowdin](https://crowdin.com/project/gogs/ru)

**Comment by mvpenzin** [comment]
@06Games , Ow.. I see so, so more errors in Crowdin.....
It upgrades my locale file easy)
And I can help translate Gogs for all)
Thanks!

**Comment by mvpenzin** [comment]
image
It's not working

**Comment by 06Games** [comment]
@Unknwon hasn't yet approved your changes. Wait a while, your changes should be approved if they get enough votes.

**Comment by Unknwon** [comment]
Thanks, the translation has been approved on the Crowdin. Will sync to main repository in a timely manner.

**Pull request closed without merging**
