### PR TITLE
Fix #1253

### LINKED ISSUE #1253: Label repos
It'd be cool if you could apply labels to repositories, and then filter repos by label, view all labels (with a button to show/hide labeled repos), etc.

Then make them cloneable as "label:<name>" (actually, idk the name restrictions on paths, so maybe this wouldn't work), which would result in a git repo with all labeled repos as submodules.

### PR DESCRIPTION
**Pull request by isundil**
Hello,

This pull request implements the feature #1253.
The only remaining thing to do is translating langs.

Regards,
isundil

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks for the PR!

Do you have screenshots?

**Comment by isundil** [comment]
Here are some screenshots from the updated pages

User / org home page
2018-06-05-215222_1108x732_scrot

Repository pages
2018-06-05-215233_1081x828_scrot

Repository setting page
2018-06-05-215329_1079x857_scrot

User setting page
2018-06-05-215345_1037x545_scrot

**Comment by Unknwon** [comment]
Thanks! Although color seems fancy, but I personally prefer the why GitHub "topic" does, feels more nature, how do you think?

**Comment by Unknwon** [comment]
But I think it is too colorful compare to the simple color scheme of Gogs main interface.

**Comment by isundil** [comment]
Yeah, I agree with you. I'll update this PR and send updated screenshot around next week.

Thanks

**Comment by SoniEx2** [comment]
can you nest these? (sub-labels)

if not, it doesn't fix #1253

**Comment by isundil** [comment]
No they are not nesteable as it would imply breaking change on the router. I feel pointless to have sub-labels and I don't know any system allowing this feature

**Comment by SoniEx2** [comment]
gmail

**Comment by SoniEx2** [comment]
on the repo, just "A/B/C".

on the label list, print it as a tree (similar to the `tree` unix command output).

**Comment by Unknwon** [comment]
I personally think no real hierarchy needed, just allow `/` in the label name is sufficient enough.

**Comment by SoniEx2** [comment]
Why nesting matters:

```
$ tree -dfi -L 2
.
./bitbucket
./bitbucket/eirc3
./bitbucket/eventbus
./bitbucket/libtransfer
./bitbucket/love
./bitbucket/lua
./bitbucket/openwithmenu
./bitbucket/rcmodrevive
```

```
$ tree -d -L 2
.
└── bitbucket
    ├── eirc3
    ├── eventbus
    ├── libtransfer
    ├── love
    ├── lua
    ├── openwithmenu
    └── rcmodrevive
```

**Comment by isundil** [comment]
I can manage the nesting simpling by storing the full name.

The pro will be an easy search access and just a minimal change in the label list instead of seaking in a database tree ;
the cons are we would need one more query when renaming or removing a label (to check their children)

**Comment by SoniEx2** [comment]
display it as a tree. and have correct removal semantics.

but for simplicity don't store it as a tree in the DB.

**Comment by ibearth2025** [comment]
Please , How can I implement those new features in normal Gogs , I means the version which is not using Docker ?

**Pull request closed without merging**
