### PR TITLE
Do not crash repo main page if the repo has no branch but has tag

### PR DESCRIPTION
**Pull request by linquize**
Do not crash repo main page if the repo has no branch but has tag

### CODE REVIEW

**Comment by Unknwon** [comment]
Hi, what is the use case that a repository doesn't have any branch but have tags?

**Comment by linquize** [comment]
After creating the repo, the user runs `git push --tags`, not `git push`

**Comment by Unknwon** [comment]
Thanks, what is the practical meaning to have tags with empty repository?

**Comment by linquize** [comment]
The user simply typed `git push --tags`. He actually wants to type something like `git push --tags origin master`

**Comment by Unknwon** [comment]
OK... make sense. I'll review it.

**Comment by linquize** [comment]
Why issue closed?  Due to commit message in 895e538?

**Comment by unknwon** [comment]
OMG, I 100% believe it didn't hit close and now even me can't reopen this PR.

Screen Shot 2019-10-25 at 11 35 58 AM

**Comment by unknwon** [comment]
OK, I think I know why... I removed use of `develop` branch, so all PR will be merged to `master`. I'm surprised by this automatic side effect with no explanation in the timeline.

**Comment by unknwon** [comment]
Thanks for rising the attention! I'm going to pull PRs with `status/waits for review` as a branch to the repository.

**Pull request closed without merging**
