### PR TITLE
Mobile-friendly interface

### LINKED ISSUE #144: Mobile specific UI
... to make them fit on mobile devices. 

Same goes with class img-responsive for images like on startpage

### PR DESCRIPTION
**Pull request by 06Games**
Fix #144 

This is just a merge proposal, I know pull requests aren't welcome for this issue but I still try my luck.
I hope this will allow you to make the mobile interface more enjoyable.

## Screenshot
repo

### CODE REVIEW

**Comment by yogicodes** [comment]
This is Awesome!

**Comment by 06Games** [comment]
I've publish a [Gits](https://gist.github.com/06Games/00177bda10c272715c83f6f989c1d078) version of this
For using it :
Copy the file named *mobile.css* to **GOGS**/public/css/
And *head.tmpl* to **GOGS**/templates/inject/head.tmpl

**Comment by ibearth2025** [comment]
really thank you , soon I'll be sharing a Expert UI desgin for contributing to GOGS

**Comment by anchengjian** [comment]
really thank you！When can you update?

**Comment by 06Games** [comment]
> @anchengjian  really thank you！When can you update?

I made some changes on the [gist](https://gist.github.com/06Games/00177bda10c272715c83f6f989c1d078) to make the css file compatible with **Gogs 0.11.66**. I haven't yet installed the **0.11.79**, so I can't tell you if it is compatible. I will install the latest version as soon as possible.

Thanks for your support

**Comment by 06Games** [comment]
I installed **Gogs 0.11.86** and it seems to be fully compatible with the [gist](https://gist.github.com/06Games/00177bda10c272715c83f6f989c1d078) version
Sorry if I have not updated this PR but I'm really lazy, if you need an update tell me but I do not have the strength to take the time to update it for nothing ...

**Pull request closed without merging**
