### PR TITLE
Slack webhook: Enclose commit message title into backticks.

### PR DESCRIPTION
**Pull request by jurajlutter**
### Describe the pull request

To prevent Slack from messing up the commit message title, enclose the message into backticks.

Link to the issue: n/a

### Checklist

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct) by submitting this pull request.
- [X] I have read and acknowledge the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).
- [ ] I have added test cases to cover the new code.

### CODE REVIEW

**Comment by jurajlutter** [comment]
I'd like to ask whether someone from approving reviewers could take a quick look to see whether this is worth to commit. Thanks.

**Review by unknwon — APPROVED** [review]
Thank you!

**Review by unknwon — CHANGES_REQUESTED** [review]
Actually, I don't think we the issue title is good to be put into backticks.

**Comment by jurajlutter** [comment]
It should at least be configurable :-) Because for my use cases, issue in backticks is preferred, for others it may not be. I'll play with the code again to make this optional.

**Pull request closed without merging**
