### PR TITLE
markdown: support rendering Mermaid diagrams

### PR DESCRIPTION
**Pull request by free1139**
Trying to support mermaid issue https://github.com/gogs/gogs/issues/4229, https://github.com/gogs/gogs/pull/6630

~~I found that need to ran `make` not `go build` to took effect.~~
`make generate && make build` for build.

Test the mermaid's diagrams were passed.
~~~
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
~~~

~~~
```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```
~~~

The renderings
image

### CODE REVIEW

**Comment by free1139** [comment]
The the plug-in size has a little big. I don't know why the browser cache doesn't work yet.

image

**Review by unknwon — APPROVED** [review]
Thanks for the PR! The changes LGTM, I just need to pull down do a sanity check locally.

**Comment by albetech** [comment]
This feature looks so incredible I tried to find a way to use it for a few hours, but it didn't work for me. 

Can you please hint me on how to enable it, if it's disabled? I tried version 0.11, 0.12.10, 0.13-dev, but none of them seem to react to mermaid syntax like illustrated in the first comment in this thread:

```
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by unknwon** [comment]
Hey @albetech - I just did some quick tests against 0.13.0+dev and confirm that mermaid currently only works for markdown files (i.e. doesn't render for issue and its comments), also "Preview" would still display as code block, I had to save and see the rendered diagram.

CleanShot 2023-01-07 at 16 32 58@2x


CleanShot 2023-01-07 at 16 33 08@2x

**Pull request merged**
